"""create QueryIndicator table

Revision ID: 056553c53121
Revises: a43051cc652f
Create Date: 2024-07-12 13:29:46.149241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056553c53121'
down_revision = 'a43051cc652f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.Enum('TOTAL_SHOWS', 'TOTAL_CLICKS', 'AVG_SHOW_POSITION', 'AVG_CLICK_POSITION', name='indicator'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_indicator')
    # ### end Alembic commands ###
