"""Add model for query

Revision ID: 187d55dec0ad
Revises: 4468c67b0fa2
Create Date: 2024-05-05 22:51:05.585272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187d55dec0ad'
down_revision = '4468c67b0fa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('impression', sa.Float(), nullable=False),
    sa.Column('demand', sa.Float(), nullable=False),
    sa.Column('clicks', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query',
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('url'),
    sa.UniqueConstraint('url')
    )
    op.create_unique_constraint(None, 'url', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='unique')
    op.drop_table('query')
    op.drop_table('metrics_query')
    # ### end Alembic commands ###
