"""Add model for query

Revision ID: 2fa81f1342e7
Revises: 187d55dec0ad
Create Date: 2024-05-12 16:01:16.899924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa81f1342e7'
down_revision = '187d55dec0ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'query', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query', type_='unique')
    # ### end Alembic commands ###
