"""Add demande in url models

Revision ID: 3a2790da30d8
Revises: edcf4b7754f7
Create Date: 2024-05-12 18:24:45.033336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2790da30d8'
down_revision = 'edcf4b7754f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('demand', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'demand')
    # ### end Alembic commands ###
