"""add count field to QueryUrlTop

Revision ID: 873b6ed9a230
Revises: 24907a842a6c
Create Date: 2024-07-24 01:01:05.488177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873b6ed9a230'
down_revision = '24907a842a6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_url_top', sa.Column('count', sa.Integer(), nullable=False, ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_url_top', 'count')
    # ### end Alembic commands ###
