"""create upgate logs query and url

Revision ID: a43051cc652f
Revises: 3a2790da30d8
Create Date: 2024-07-10 18:06:14.999216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43051cc652f'
down_revision = '3a2790da30d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_logs_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_logs_url',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_logs_url')
    op.drop_table('update_logs_query')
    # ### end Alembic commands ###
