"""create QueryUrlsMerge abd QueryUrlsMergeLogs

Revision ID: c25f17540c5c
Revises: 87b4cab61fd7
Create Date: 2024-07-17 22:14:17.759932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25f17540c5c'
down_revision = '87b4cab61fd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_urls_merge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('queries', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'url')
    )
    op.create_table('query_urls_merge_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_urls_merge_logs')
    op.drop_table('query_urls_merge')
    # ### end Alembic commands ###
