"""Change lable query field from url to query

Revision ID: edcf4b7754f7
Revises: 2fa81f1342e7
Create Date: 2024-05-12 16:17:54.532597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcf4b7754f7'
down_revision = '2fa81f1342e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics_query', sa.Column('query', sa.String(), nullable=False))
    op.drop_column('metrics_query', 'url')
    op.add_column('query', sa.Column('query', sa.String(), nullable=False))
    op.drop_constraint('query_url_key', 'query', type_='unique')
    op.create_unique_constraint(None, 'query', ['query'])
    op.drop_column('query', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'query', type_='unique')
    op.create_unique_constraint('query_url_key', 'query', ['url'])
    op.drop_column('query', 'query')
    op.add_column('metrics_query', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('metrics_query', 'query')
    # ### end Alembic commands ###
