"""create UpdateLogsIndicator table

Revision ID: fe59ac7f0341
Revises: 056553c53121
Create Date: 2024-07-12 13:35:42.773884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe59ac7f0341'
down_revision = '056553c53121'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_logs_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_logs_indicator')
    # ### end Alembic commands ###
