"""add cascade delete for user-query relaionship

Revision ID: 0a6c4ced02cf
Revises: 7715caf98e70
Create Date: 2024-09-14 15:15:10.811546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6c4ced02cf'
down_revision: Union[str, None] = '7715caf98e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_query_count_user_id_fkey', 'user_query_count', type_='foreignkey')
    op.create_foreign_key(None, 'user_query_count', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_query_count', type_='foreignkey')
    op.create_foreign_key('user_query_count_user_id_fkey', 'user_query_count', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
