"""add cascad for ListLrSearchSystem

Revision ID: 0c07329eada3
Revises: eb2bf4c68df9
Create Date: 2024-09-02 14:21:44.055084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c07329eada3'
down_revision: Union[str, None] = 'eb2bf4c68df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('query_live_search_google_lr_list_id_fkey', 'query_live_search_google', type_='foreignkey')
    op.create_foreign_key(None, 'query_live_search_google', 'list_lr_search_system', ['lr_list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('query_live_search_yandex_lr_list_id_fkey', 'query_live_search_yandex', type_='foreignkey')
    op.create_foreign_key(None, 'query_live_search_yandex', 'list_lr_search_system', ['lr_list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_live_search_yandex', type_='foreignkey')
    op.create_foreign_key('query_live_search_yandex_lr_list_id_fkey', 'query_live_search_yandex', 'list_lr_search_system', ['lr_list_id'], ['id'])
    op.drop_constraint(None, 'query_live_search_google', type_='foreignkey')
    op.create_foreign_key('query_live_search_google_lr_list_id_fkey', 'query_live_search_google', 'list_lr_search_system', ['lr_list_id'], ['id'])
    # ### end Alembic commands ###
