"""add live search tables

Revision ID: 19c4538f11bb
Revises: aebb936cffc4
Create Date: 2024-08-28 15:17:12.284317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c4538f11bb'
down_revision: Union[str, None] = 'aebb936cffc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_search_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('main_domain', sa.String(), nullable=False),
    sa.Column('lr', sa.Integer(), nullable=False),
    sa.Column('search_system', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_search_list_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['live_search_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_live_search_google',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query'], ['live_search_list_query.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_live_search_yandex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query'], ['live_search_list_query.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_query_count',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_query_count')
    op.drop_table('query_live_search_yandex')
    op.drop_table('query_live_search_google')
    op.drop_table('live_search_list_query')
    op.drop_table('live_search_list')
    # ### end Alembic commands ###
