"""add position field

Revision ID: 1e6687648fb1
Revises: f294a5452835
Create Date: 2024-08-28 17:43:32.480002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6687648fb1'
down_revision: Union[str, None] = 'f294a5452835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_live_search_google', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('query_live_search_yandex', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_live_search_yandex', 'position')
    op.drop_column('query_live_search_google', 'position')
    # ### end Alembic commands ###
