"""change relationship

Revision ID: 40956d118891
Revises: a104a9e1b4b3
Create Date: 2024-09-01 14:39:24.051028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40956d118891'
down_revision: Union[str, None] = 'a104a9e1b4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_search_list_query', sa.Column('list_id', sa.Integer(), nullable=False))
    op.drop_constraint('live_search_list_query_list_lr_search_id_fkey', 'live_search_list_query', type_='foreignkey')
    op.create_foreign_key(None, 'live_search_list_query', 'live_search_list', ['list_id'], ['id'])
    op.drop_column('live_search_list_query', 'list_lr_search_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_search_list_query', sa.Column('list_lr_search_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'live_search_list_query', type_='foreignkey')
    op.create_foreign_key('live_search_list_query_list_lr_search_id_fkey', 'live_search_list_query', 'list_lr_search_system', ['list_lr_search_id'], ['id'])
    op.drop_column('live_search_list_query', 'list_id')
    # ### end Alembic commands ###
