"""add list_lr_id field in yandex & google table

Revision ID: 47a4952811f9
Revises: 40956d118891
Create Date: 2024-09-01 15:37:51.446057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a4952811f9'
down_revision: Union[str, None] = '40956d118891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_live_search_google', sa.Column('lr_list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'query_live_search_google', 'list_lr_search_system', ['lr_list_id'], ['id'])
    op.add_column('query_live_search_yandex', sa.Column('lr_list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'query_live_search_yandex', 'list_lr_search_system', ['lr_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_live_search_yandex', type_='foreignkey')
    op.drop_column('query_live_search_yandex', 'lr_list_id')
    op.drop_constraint(None, 'query_live_search_google', type_='foreignkey')
    op.drop_column('query_live_search_google', 'lr_list_id')
    # ### end Alembic commands ###
