"""change username field to nullable=True

Revision ID: 7715caf98e70
Revises: 0fd4b4772302
Create Date: 2024-09-14 01:15:34.870082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7715caf98e70'
down_revision: Union[str, None] = '0fd4b4772302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###
