"""Apply changes to Role table

Revision ID: 78767a5b4e57
Revises: 7fb9546a6052
Create Date: 2024-09-26 13:34:52.945880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78767a5b4e57'
down_revision: Union[str, None] = '7fb9546a6052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('access_queries', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_queries_full', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_queries_view', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_queries_filter', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_queries_export', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_queries_update', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_queries_sum', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_full', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_filter', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_export', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_update', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_sum', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_history', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_history_full', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_history_view', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_history_export', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_query_merge', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_query_merge_full', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_query_merge_view', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_url_query_merge_run', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_list_panel', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_list_panel_full', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_list_panel_create', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_list_panel_edit', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_list_panel_share', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_command_panel', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_command_panel_full', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_command_panel_own', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_live_search', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_live_search_full', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_live_search_use', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_user_menu', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('access_group_menu', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'access_group_menu')
    op.drop_column('roles', 'access_user_menu')
    op.drop_column('roles', 'access_live_search_use')
    op.drop_column('roles', 'access_live_search_full')
    op.drop_column('roles', 'access_live_search')
    op.drop_column('roles', 'access_command_panel_own')
    op.drop_column('roles', 'access_command_panel_full')
    op.drop_column('roles', 'access_command_panel')
    op.drop_column('roles', 'access_list_panel_share')
    op.drop_column('roles', 'access_list_panel_edit')
    op.drop_column('roles', 'access_list_panel_create')
    op.drop_column('roles', 'access_list_panel_full')
    op.drop_column('roles', 'access_list_panel')
    op.drop_column('roles', 'access_url_query_merge_run')
    op.drop_column('roles', 'access_url_query_merge_view')
    op.drop_column('roles', 'access_url_query_merge_full')
    op.drop_column('roles', 'access_url_query_merge')
    op.drop_column('roles', 'access_history_export')
    op.drop_column('roles', 'access_history_view')
    op.drop_column('roles', 'access_history_full')
    op.drop_column('roles', 'access_history')
    op.drop_column('roles', 'access_url_sum')
    op.drop_column('roles', 'access_url_update')
    op.drop_column('roles', 'access_url_export')
    op.drop_column('roles', 'access_url_filter')
    op.drop_column('roles', 'access_url_full')
    op.drop_column('roles', 'access_url')
    op.drop_column('roles', 'access_queries_sum')
    op.drop_column('roles', 'access_queries_update')
    op.drop_column('roles', 'access_queries_export')
    op.drop_column('roles', 'access_queries_filter')
    op.drop_column('roles', 'access_queries_view')
    op.drop_column('roles', 'access_queries_full')
    op.drop_column('roles', 'access_queries')
    # ### end Alembic commands ###
