"""add ListLrSearchSystem model & update relationship

Revision ID: 895b751c4c6a
Revises: 788ead7f5c11
Create Date: 2024-08-31 21:12:44.354614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895b751c4c6a'
down_revision: Union[str, None] = '788ead7f5c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_lr_search_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('lr', sa.Integer(), nullable=False),
    sa.Column('search_system', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['live_search_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('live_search_list', 'search_system')
    op.drop_column('live_search_list', 'lr')
    op.add_column('live_search_list_query', sa.Column('list_lr_search_id', sa.Integer(), nullable=False))
    op.drop_constraint('live_search_list_query_list_id_fkey', 'live_search_list_query', type_='foreignkey')
    op.drop_constraint('fk_live_search_list_query_list_id_live_search_list', 'live_search_list_query', type_='foreignkey')
    op.create_foreign_key(None, 'live_search_list_query', 'list_lr_search_system', ['list_lr_search_id'], ['id'])
    op.drop_column('live_search_list_query', 'list_id')
    op.add_column('query_live_search_google', sa.Column('query_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_query_live_search_google_query_live_search_list_query', 'query_live_search_google', type_='foreignkey')
    op.drop_constraint('query_live_search_google_query_fkey', 'query_live_search_google', type_='foreignkey')
    op.create_foreign_key(None, 'query_live_search_google', 'live_search_list_query', ['query_id'], ['id'])
    op.drop_column('query_live_search_google', 'query')
    op.add_column('query_live_search_yandex', sa.Column('query_id', sa.Integer(), nullable=False))
    op.drop_constraint('query_live_search_yandex_query_fkey', 'query_live_search_yandex', type_='foreignkey')
    op.drop_constraint('fk_query_live_search_yandex_query_live_search_list_query', 'query_live_search_yandex', type_='foreignkey')
    op.create_foreign_key(None, 'query_live_search_yandex', 'live_search_list_query', ['query_id'], ['id'])
    op.drop_column('query_live_search_yandex', 'query')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_live_search_yandex', sa.Column('query', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'query_live_search_yandex', type_='foreignkey')
    op.create_foreign_key('fk_query_live_search_yandex_query_live_search_list_query', 'query_live_search_yandex', 'live_search_list_query', ['query'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('query_live_search_yandex_query_fkey', 'query_live_search_yandex', 'live_search_list_query', ['query'], ['id'])
    op.drop_column('query_live_search_yandex', 'query_id')
    op.add_column('query_live_search_google', sa.Column('query', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'query_live_search_google', type_='foreignkey')
    op.create_foreign_key('query_live_search_google_query_fkey', 'query_live_search_google', 'live_search_list_query', ['query'], ['id'])
    op.create_foreign_key('fk_query_live_search_google_query_live_search_list_query', 'query_live_search_google', 'live_search_list_query', ['query'], ['id'], ondelete='CASCADE')
    op.drop_column('query_live_search_google', 'query_id')
    op.add_column('live_search_list_query', sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'live_search_list_query', type_='foreignkey')
    op.create_foreign_key('fk_live_search_list_query_list_id_live_search_list', 'live_search_list_query', 'live_search_list', ['list_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('live_search_list_query_list_id_fkey', 'live_search_list_query', 'live_search_list', ['list_id'], ['id'])
    op.drop_column('live_search_list_query', 'list_lr_search_id')
    op.add_column('live_search_list', sa.Column('lr', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('live_search_list', sa.Column('search_system', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('list_lr_search_system')
    # ### end Alembic commands ###
