"""add Role table

Revision ID: b522be0c9e66
Revises: 5954b59ad60a
Create Date: 2024-08-14 11:19:34.902442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b522be0c9e66'
down_revision: Union[str, None] = '5954b59ad60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('config', 'user')
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role')
    op.add_column('config', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('roles')
    # ### end Alembic commands ###
