"""Added Role Access model, changed role model

Revision ID: e68605e96d43
Revises: 78767a5b4e57
Create Date: 2024-10-01 14:38:25.635924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68605e96d43'
down_revision: Union[str, None] = '78767a5b4e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('queries_full', sa.Boolean(), nullable=True),
    sa.Column('queries_view', sa.Boolean(), nullable=True),
    sa.Column('queries_filter', sa.Boolean(), nullable=True),
    sa.Column('queries_export', sa.Boolean(), nullable=True),
    sa.Column('queries_update', sa.Boolean(), nullable=True),
    sa.Column('queries_sum', sa.Boolean(), nullable=True),
    sa.Column('url_full', sa.Boolean(), nullable=True),
    sa.Column('url_view', sa.Boolean(), nullable=True),
    sa.Column('url_filter', sa.Boolean(), nullable=True),
    sa.Column('url_export', sa.Boolean(), nullable=True),
    sa.Column('url_update', sa.Boolean(), nullable=True),
    sa.Column('url_sum', sa.Boolean(), nullable=True),
    sa.Column('history_full', sa.Boolean(), nullable=True),
    sa.Column('history_view', sa.Boolean(), nullable=True),
    sa.Column('history_export', sa.Boolean(), nullable=True),
    sa.Column('url_query_merge_full', sa.Boolean(), nullable=True),
    sa.Column('url_query_merge_view', sa.Boolean(), nullable=True),
    sa.Column('url_query_merge_run', sa.Boolean(), nullable=True),
    sa.Column('list_panel_full', sa.Boolean(), nullable=True),
    sa.Column('list_panel_view', sa.Boolean(), nullable=True),
    sa.Column('list_panel_create', sa.Boolean(), nullable=True),
    sa.Column('list_panel_edit', sa.Boolean(), nullable=True),
    sa.Column('list_panel_share', sa.Boolean(), nullable=True),
    sa.Column('command_panel_full', sa.Boolean(), nullable=True),
    sa.Column('command_panel_own', sa.Boolean(), nullable=True),
    sa.Column('live_search_full', sa.Boolean(), nullable=True),
    sa.Column('live_search_use', sa.Boolean(), nullable=True),
    sa.Column('user_full', sa.Boolean(), nullable=True),
    sa.Column('group_full', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('roles', 'access_queries_sum')
    op.drop_column('roles', 'access_url_query_merge_full')
    op.drop_column('roles', 'access_history_view')
    op.drop_column('roles', 'access_url_sum')
    op.drop_column('roles', 'access_history_export')
    op.drop_column('roles', 'access_live_search_full')
    op.drop_column('roles', 'access_list_panel_full')
    op.drop_column('roles', 'access_queries_filter')
    op.drop_column('roles', 'access_queries_full')
    op.drop_column('roles', 'access_url_update')
    op.drop_column('roles', 'access_history_full')
    op.drop_column('roles', 'access_history')
    op.drop_column('roles', 'access_command_panel_full')
    op.drop_column('roles', 'access_command_panel_own')
    op.drop_column('roles', 'access_queries_update')
    op.drop_column('roles', 'access_url_query_merge_view')
    op.drop_column('roles', 'access_list_panel_edit')
    op.drop_column('roles', 'access_live_search_use')
    op.drop_column('roles', 'access_live_search')
    op.drop_column('roles', 'access_list_panel')
    op.drop_column('roles', 'access_url_full')
    op.drop_column('roles', 'access_list_panel_share')
    op.drop_column('roles', 'access_url_query_merge_run')
    op.drop_column('roles', 'access_queries_export')
    op.drop_column('roles', 'access_url_filter')
    op.drop_column('roles', 'access_command_panel')
    op.drop_column('roles', 'access_queries')
    op.drop_column('roles', 'access_url_export')
    op.drop_column('roles', 'access_url')
    op.drop_column('roles', 'access_user_menu')
    op.drop_column('roles', 'access_group_menu')
    op.drop_column('roles', 'access_queries_view')
    op.drop_column('roles', 'access_list_panel_create')
    op.drop_column('roles', 'access_url_query_merge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('access_url_query_merge', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_list_panel_create', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_queries_view', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_group_menu', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_user_menu', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url_export', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_queries', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_command_panel', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url_filter', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_queries_export', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url_query_merge_run', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_list_panel_share', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url_full', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_list_panel', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_live_search', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_live_search_use', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_list_panel_edit', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url_query_merge_view', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_queries_update', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_command_panel_own', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_command_panel_full', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_history', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_history_full', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url_update', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_queries_full', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_queries_filter', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_list_panel_full', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_live_search_full', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_history_export', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url_sum', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_history_view', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_url_query_merge_full', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('access_queries_sum', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_table('role_access')
    # ### end Alembic commands ###
