"""Added Config-User relationship

Revision ID: e8987d5f4dc4
Revises: ebb71f9593ed
Create Date: 2024-10-04 16:19:06.814704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8987d5f4dc4'
down_revision: Union[str, None] = 'ebb71f9593ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'config', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'config', type_='foreignkey')
    op.drop_column('config', 'author_id')
    # ### end Alembic commands ###
