"""Create YandexLr table

Revision ID: eb2bf4c68df9
Revises: 47a4952811f9
Create Date: 2024-09-01 16:19:52.862491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2bf4c68df9'
down_revision: Union[str, None] = '47a4952811f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yandex_lr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Geo', sa.String(), nullable=False),
    sa.Column('Geoid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yandex_lr')
    # ### end Alembic commands ###
