"""add author field for live search

Revision ID: f294a5452835
Revises: 19c4538f11bb
Create Date: 2024-08-28 16:06:46.526998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f294a5452835'
down_revision: Union[str, None] = '19c4538f11bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_search_list', sa.Column('author', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'live_search_list', 'user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'live_search_list', type_='foreignkey')
    op.drop_column('live_search_list', 'author')
    # ### end Alembic commands ###
